# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.spec.v1.openapi_server.models.base_model_ import Model
from api.spec.v1.openapi_server import util


class User(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, unit=None, salary=None):  # noqa: E501
        """User - a model defined in OpenAPI

        :param id: The id of this User.  # noqa: E501
        :type id: int
        :param name: The name of this User.  # noqa: E501
        :type name: str
        :param unit: The unit of this User.  # noqa: E501
        :type unit: str
        :param salary: The salary of this User.  # noqa: E501
        :type salary: float
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'unit': str,
            'salary': float
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'unit': 'unit',
            'salary': 'salary'
        }

        self._id = id
        self._name = name
        self._unit = unit
        self._salary = salary

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this User.


        :return: The id of this User.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this User.


        :param id: The id of this User.
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this User.


        :return: The name of this User.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this User.


        :param name: The name of this User.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def unit(self):
        """Gets the unit of this User.


        :return: The unit of this User.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this User.


        :param unit: The unit of this User.
        :type unit: str
        """
        if unit is None:
            raise ValueError("Invalid value for `unit`, must not be `None`")  # noqa: E501

        self._unit = unit

    @property
    def salary(self):
        """Gets the salary of this User.


        :return: The salary of this User.
        :rtype: float
        """
        return self._salary

    @salary.setter
    def salary(self, salary):
        """Sets the salary of this User.


        :param salary: The salary of this User.
        :type salary: float
        """
        if salary is None:
            raise ValueError("Invalid value for `salary`, must not be `None`")  # noqa: E501

        self._salary = salary
