apiVersion: v1
kind: Service
metadata:
  name: usersopenapi-svc
  labels:
    app: usersopenapi-lbl
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: usersopenapi-lbl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersopenapi-dpl
  labels:
    app: usersopenapi-lbl
spec:
  selector:
    matchLabels:
      app: usersopenapi-lbl
  replicas: 1
  template:
    metadata:
      labels:
        app: usersopenapi-lbl
    spec:
      containers:
        - name: usersopenapi
          image: shpboris/usersopenapi
          ports:
            - containerPort: 8080
              protocol: TCP
