apiVersion: v1
kind: Service
metadata:
  name: usersopenapi-svc
  labels:
    app: usersopenapi-lbl
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: usersopenapi-lbl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersopenapi-dpl
  labels:
    app: usersopenapi-lbl
spec:
  selector:
    matchLabels:
      app: usersopenapi-lbl
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'mywebappk'
        vault.hashicorp.com/agent-inject-secret-config.txt: 'secret/mywebapp/conf'
        vault.hashicorp.com/agent-inject-template-config.txt: |
          {{ with secret "secret/mywebapp/conf" }}
          host=localhost
          port=1433
          user={{ .Data.data.myuser }}
          pass={{ .Data.data.mypass }}
          {{ end }}
      labels:
        app: usersopenapi-lbl
    spec:
      serviceAccountName: myserviceacc
      containers:
        - name: usersopenapi
          image: shpboris/usersopenapi
          ports:
            - containerPort: 8080
              protocol: TCP
