apiVersion: v1
kind: Service
metadata:
  name: usersopenapi-svc
  labels:
    app: usersopenapi-lbl
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: usersopenapi-lbl