version: 1
formatters:
  simple:
    format: '%(asctime)s [%(levelname)s] %(filename)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: app.log
loggers:
  root:
    level: INFO
    handlers: [console, file]
